---
apiVersion: v1
kind: Secret
metadata:
  name: cloud-config
  namespace: kube-system
stringData:
  config.yaml: |
    opennebula:
      endpoint:
        ONE_XMLRPC: "${ONE_XMLRPC}"
        ONE_AUTH: "${ONE_AUTH}"
      publicNetwork:
        name: "${PUBLIC_NETWORK_NAME}"
      privateNetwork:
        name: "${PRIVATE_NETWORK_NAME}"
      virtualRouter:
        templateName: "${ROUTER_TEMPLATE_NAME}"
        extraContext: {}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: opennebula-cloud-controller-manager
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:opennebula-cloud-controller-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: opennebula-cloud-controller-manager
    namespace: kube-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    k8s-app: cloud-controller-manager
  name: cloud-controller-manager
  namespace: kube-system
spec:
  selector:
    matchLabels:
      k8s-app: cloud-controller-manager
  template:
    metadata:
      labels:
        k8s-app: cloud-controller-manager
    spec:
      serviceAccountName: opennebula-cloud-controller-manager
      containers:
        - name: cloud-controller-manager
          image: "${CCM_IMG}"
          command:
            - /opennebula-cloud-controller-manager
            - --cloud-provider=opennebula
            - --cluster-name=$(CLUSTER_NAME)
            - --cloud-config=/etc/one/config.yaml
            - --leader-elect=true
            - --use-service-account-credentials
            - --controllers=cloud-node,cloud-node-lifecycle,service-lb-controller
          volumeMounts:
            - name: cloud-config
              mountPath: /etc/one/
              readOnly: true
      volumes:
        - name: cloud-config
          secret:
            secretName: cloud-config
      hostNetwork: true
      tolerations:
        - key: node.cloudprovider.kubernetes.io/uninitialized
          value: "true"
          effect: NoSchedule
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
        - key: CriticalAddonsOnly
          operator: Equal
          value: "true"
          effect: NoExecute
        # TODO: remove this one later!
        - key: node.kubernetes.io/not-ready
          operator: Exists
          effect: NoSchedule
      nodeSelector:
        node-role.kubernetes.io/control-plane: "true"
